[config]
schemaVersion = "0.0.1"

[package]
namespace = "CaptainOfCoit"
name = "CityMonitor"
versionNumber = "0.2.0"
description = "A little panel with the most important metrics of your city without having to browse around"
websiteUrl = "https://thunderstore.io"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
CaptainOfCoit-HookUI = "0.3.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./ts-build"

[publish]
repository = "https://thunderstore.io"
communities = [ "cities-skylines-ii", ]
categories = [ "mods" ]
