name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '21.1.0'
    - run: npm ci
    - run: make package-unix && ls && ls dist/