name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build project
      uses: actions/setup-node@v3
      with:
        node-version: '21.1.0'
    - run: make package-unix && ls && ls dist/
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-file.zip
        path: dist/release-*.zip